export const STORAGE_KEYS = {
  session: "laundryos.session",
  laundries: "laundryos.laundries",
  branches: "laundryos.branches",
  customers: "laundryos.customers",
  itemGroups: "laundryos.itemGroups",
  serviceItems: "laundryos.serviceItems",
  timeSlots: "laundryos.timeSlots",
  orders: "laundryos.orders",
  paymentReceipts: "laundryos.paymentReceipts",
  recentBranch: "laundryos.recentBranch",
};

export const demoUsers = [
  {
    id: "user-super",
    name: "Maya Chen",
    email: "super@laundryos.test",
    password: "Super@2026",
    role: "Super Admin",
    loginType: "super-admin",
    permissions: ["manage_platform"],
  },
  {
    id: "user-owner",
    name: "Arjun Mehta",
    email: "owner@freshfold.test",
    password: "Owner@2026",
    role: "Laundry Owner",
    loginType: "business",
    laundryId: "laundry-1",
    permissions: ["create_branch", "manage_staff", "create_order", "manage_payments"],
    branchIds: ["branch-1", "branch-2"],
  },
  {
    id: "user-owner-empty",
    name: "Nora Blake",
    email: "newowner@laundryos.test",
    password: "Owner@2026",
    role: "Laundry Owner",
    loginType: "business",
    laundryId: "laundry-3",
    permissions: ["create_branch", "manage_staff", "create_order"],
    branchIds: [],
  },
  {
    id: "user-staff",
    name: "Leah Carter",
    email: "staff@freshfold.test",
    password: "Staff@2026",
    role: "Branch Staff",
    loginType: "business",
    laundryId: "laundry-1",
    permissions: ["create_order", "record_payment"],
    branchIds: ["branch-1"],
  },
];

export const initialLaundries = [
  {
    id: "laundry-1",
    name: "FreshFold Laundry",
    email: "hello@freshfold.test",
    phone: "+1 415 555 0182",
    registrationNumber: "FF-20491",
    address: "210 Market Street",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94105",
    plan: "Growth",
    status: "Active",
    ownerName: "Arjun Mehta",
    ownerEmail: "owner@freshfold.test",
    ownerPhone: "+1 415 555 0199",
    ownerStatus: "Active",
    logo: "",
    createdAt: "2026-09-02",
    subscription: "Active",
  },
  {
    id: "laundry-2",
    name: "BlueWave Cleaners",
    email: "ops@bluewave.test",
    phone: "+1 212 555 0164",
    registrationNumber: "BW-11870",
    address: "88 Hudson Avenue",
    city: "New York",
    state: "NY",
    country: "United States",
    postalCode: "10013",
    plan: "Enterprise",
    status: "Active",
    ownerName: "Priya Nair",
    ownerEmail: "owner@bluewave.test",
    ownerPhone: "+1 212 555 0190",
    ownerStatus: "Active",
    logo: "",
    createdAt: "2026-08-18",
    subscription: "Active",
  },
  {
    id: "laundry-3",
    name: "UrbanPress Laundry",
    email: "team@urbanpress.test",
    phone: "+1 312 555 0147",
    registrationNumber: "UP-33002",
    address: "42 Lakeview Road",
    city: "Chicago",
    state: "IL",
    country: "United States",
    postalCode: "60601",
    plan: "Starter",
    status: "Draft",
    ownerName: "Nora Blake",
    ownerEmail: "newowner@laundryos.test",
    ownerPhone: "+1 312 555 0188",
    ownerStatus: "Active",
    logo: "",
    createdAt: "2026-09-10",
    subscription: "Trial",
  },
];

export const initialBranches = [
  {
    id: "branch-1",
    laundryId: "laundry-1",
    name: "FreshFold Downtown",
    code: "FFD-001",
    email: "downtown@freshfold.test",
    phone: "+1 415 555 0111",
    address: "210 Market Street",
    city: "San Francisco",
    state: "CA",
    postalCode: "94105",
    openingTime: "08:00",
    closingTime: "21:00",
    manager: "Leah Carter",
    staffCount: 14,
    status: "Active",
  },
  {
    id: "branch-2",
    laundryId: "laundry-1",
    name: "FreshFold Mission",
    code: "FFM-002",
    email: "mission@freshfold.test",
    phone: "+1 415 555 0150",
    address: "550 Valencia Street",
    city: "San Francisco",
    state: "CA",
    postalCode: "94110",
    openingTime: "09:00",
    closingTime: "20:00",
    manager: "Mateo Ruiz",
    staffCount: 9,
    status: "Inactive",
  },
  {
    id: "branch-3",
    laundryId: "laundry-2",
    name: "BlueWave Tribeca",
    code: "BWT-001",
    email: "tribeca@bluewave.test",
    phone: "+1 212 555 0120",
    address: "88 Hudson Avenue",
    city: "New York",
    state: "NY",
    postalCode: "10013",
    openingTime: "07:30",
    closingTime: "22:00",
    manager: "Owen Grant",
    staffCount: 18,
    status: "Active",
  },
];

export const orderRows = [
  { id: "ORD-2401", customer: "Emma Wilson", service: "Wash & Fold", status: "In progress", total: "$42.80", due: "2:30 PM" },
  { id: "ORD-2402", customer: "Noah Kim", service: "Dry cleaning", status: "Ready", total: "$86.00", due: "4:00 PM" },
  { id: "ORD-2403", customer: "Ava Patel", service: "Ironing", status: "Pending", total: "$24.50", due: "5:15 PM" },
  { id: "ORD-2404", customer: "Lucas Brown", service: "Express wash", status: "Completed", total: "$31.20", due: "Done" },
];

export const initialCustomers = [
  {
    id: "customer-1",
    laundryId: "laundry-1",
    branchId: "branch-1",
    name: "Emma Wilson",
    phone: "+1 415 555 0101",
    email: "emma@example.test",
    address: "18 Pine Street, San Francisco",
  },
  {
    id: "customer-2",
    laundryId: "laundry-1",
    branchId: "branch-1",
    name: "Noah Kim",
    phone: "+1 415 555 0102",
    email: "noah@example.test",
    address: "44 Mission Road, San Francisco",
  },
  {
    id: "customer-3",
    laundryId: "laundry-1",
    branchId: "branch-2",
    name: "Ava Patel",
    phone: "+1 415 555 0103",
    email: "ava@example.test",
    address: "72 Valencia Street, San Francisco",
  },
];

export const initialItemGroups = [
  { id: "group-1", laundryId: "laundry-1", name: "Wash Services", status: "Active" },
  { id: "group-2", laundryId: "laundry-1", name: "Dry Cleaning", status: "Active" },
  { id: "group-3", laundryId: "laundry-1", name: "Finishing", status: "Active" },
];

export const initialServiceItems = [
  {
    id: "item-1",
    laundryId: "laundry-1",
    name: "Wash & Fold",
    shortCode: "WAF",
    groupId: "group-1",
    pricingMethod: "Per kilogram",
    price: 6.5,
    unitType: "Kilogram",
    status: "Active",
  },
  {
    id: "item-2",
    laundryId: "laundry-1",
    name: "Shirt Dry Clean",
    shortCode: "SDC",
    groupId: "group-2",
    pricingMethod: "Fixed price",
    price: 8,
    unitType: "Quantity",
    status: "Active",
  },
  {
    id: "item-3",
    laundryId: "laundry-1",
    name: "Steam Ironing",
    shortCode: "STI",
    groupId: "group-3",
    pricingMethod: "Fixed price",
    price: 4.5,
    unitType: "Quantity",
    status: "Active",
  },
];

export const initialTimeSlots = [
  { id: "slot-1", laundryId: "laundry-1", label: "09:00 AM - 11:00 AM", status: "Active" },
  { id: "slot-2", laundryId: "laundry-1", label: "11:00 AM - 01:00 PM", status: "Active" },
  { id: "slot-3", laundryId: "laundry-1", label: "02:00 PM - 04:00 PM", status: "Active" },
  { id: "slot-4", laundryId: "laundry-1", label: "04:00 PM - 06:00 PM", status: "Active" },
];

export const initialOrders = [
  {
    id: "order-1",
    orderNumber: "ORD-2601",
    laundryId: "laundry-1",
    branchId: "branch-1",
    customerId: "customer-1",
    customerName: "Emma Wilson",
    customerPhone: "+1 415 555 0101",
    customerEmail: "emma@example.test",
    customerAddress: "18 Pine Street, San Francisco",
    deliveryDate: "2026-09-17",
    deliveryTimeSlot: "02:00 PM - 04:00 PM",
    status: "Processing",
    items: [
      { rowId: "row-1", itemId: "item-1", itemName: "Wash & Fold", shortCode: "WAF", quantity: 4, unitPrice: 6.5, itemCount: 8, unitType: "Kilogram", itemTotal: 26 },
      { rowId: "row-2", itemId: "item-3", itemName: "Steam Ironing", shortCode: "STI", quantity: 3, unitPrice: 4.5, itemCount: 3, unitType: "Quantity", itemTotal: 13.5 },
    ],
    itemCount: 11,
    totalItemQuantity: 7,
    subTotal: 39.5,
    discount: 2,
    grandTotal: 37.5,
    paidAmount: 20,
    paymentStatus: "Partial",
    createdAt: "2026-09-16",
  },
  {
    id: "order-2",
    orderNumber: "ORD-2602",
    laundryId: "laundry-1",
    branchId: "branch-1",
    customerId: "customer-2",
    customerName: "Noah Kim",
    customerPhone: "+1 415 555 0102",
    customerEmail: "noah@example.test",
    customerAddress: "44 Mission Road, San Francisco",
    deliveryDate: "2026-09-16",
    deliveryTimeSlot: "04:00 PM - 06:00 PM",
    status: "Pending Delivery",
    items: [
      { rowId: "row-1", itemId: "item-2", itemName: "Shirt Dry Clean", shortCode: "SDC", quantity: 5, unitPrice: 8, itemCount: 5, unitType: "Quantity", itemTotal: 40 },
    ],
    itemCount: 5,
    totalItemQuantity: 5,
    subTotal: 40,
    discount: 0,
    grandTotal: 40,
    paidAmount: 40,
    paymentStatus: "Paid",
    createdAt: "2026-09-16",
  },
];

export const initialPaymentReceipts = [
  {
    id: "receipt-1",
    orderId: "order-1",
    amount: 20,
    method: "Cash",
    note: "Advance payment",
    paidAt: "2026-09-16",
  },
  {
    id: "receipt-2",
    orderId: "order-2",
    amount: 40,
    method: "Card",
    note: "Paid in full",
    paidAt: "2026-09-16",
  },
];

export const systemActivity = [
  "FreshFold Downtown activated online payment collection.",
  "BlueWave Cleaners upgraded to Enterprise.",
  "New branch invite sent to Mateo Ruiz.",
  "UrbanPress Laundry saved as draft.",
];
